"""Generate a current-state vs proposed-state QMS system diagram.

Outputs:
- qms_system_diagram.mmd  (Mermaid source)
- qms_system_diagram.md   (Markdown with embedded Mermaid)
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Node:
    node_id: str
    label: str
    css_class: str


@dataclass(frozen=True)
class Edge:
    src: str
    dst: str
    label: str = ""
    style: str = "solid"  # solid | dashed


def normalize_label(text: str) -> str:
    return text.replace("\n", "<br/>").replace('"', "'").replace("|", "/")


def render_node(node: Node) -> str:
    return f"    {node.node_id}[\"{normalize_label(node.label)}\"]"


def render_edge(edge: Edge) -> str:
    label = normalize_label(edge.label)
    if edge.style == "dashed":
        if label:
            return f"{edge.src} -. {label} .-> {edge.dst}"
        return f"{edge.src} -.-> {edge.dst}"

    if label:
        return f"{edge.src} -->|{label}| {edge.dst}"
    return f"{edge.src} --> {edge.dst}"


def build_mermaid() -> str:
    current_nodes = [
        Node("C_QMS", "QMS Core Governance\nManual + SOP ownership", "current"),
        Node("C_DOC", "Document Control\nShared folders + templates", "current"),
        Node("C_EVENT", "Quality Events\nDeviation / NC / Complaint", "current"),
        Node("C_CAPA", "CAPA + Change Control\nManual routing", "current"),
        Node("C_TRAIN", "Training Management\nLMS + spreadsheet evidence", "current"),
        Node("C_AUDIT", "Audit Management\nInternal + supplier audits", "current"),
        Node("C_RISK", "Risk Reviews\nPeriodic FMEA updates", "current"),
        Node("C_DATA", "Quality Reporting\nSiloed data + lagging KPIs", "current"),
        Node("C_APPROVAL", "Approvals\nEmail + wet signatures", "current"),
    ]

    current_edges = [
        Edge("C_QMS", "C_DOC"),
        Edge("C_DOC", "C_EVENT"),
        Edge("C_EVENT", "C_CAPA"),
        Edge("C_CAPA", "C_TRAIN"),
        Edge("C_CAPA", "C_AUDIT"),
        Edge("C_AUDIT", "C_RISK"),
        Edge("C_RISK", "C_QMS", "policy updates"),
        Edge("C_EVENT", "C_DATA", "manual aggregation"),
        Edge("C_CAPA", "C_DATA", "monthly reporting"),
        Edge("C_APPROVAL", "C_DOC"),
        Edge("C_APPROVAL", "C_CAPA"),
    ]

    proposed_nodes = [
        Node("P_GOV", "Governance + Compliance Controls\nPart 11 / Annex 11", "governance"),
        Node("P_ORCH", "Digital Process Orchestration\nBPMN workflows + SLA timers", "proposed"),
        Node("P_DMS", "Controlled Content Service\nVersioning + e-signature", "proposed"),
        Node("P_EQMS", "Unified eQMS Case Hub\nDeviation / CAPA / Change / Complaint", "proposed"),
        Node("P_AI", "AI Quality Copilot\nClassification + risk scoring", "ai"),
        Node("P_TRAIN", "Competency Automation\nRole impact + retraining triggers", "proposed"),
        Node("P_AUDIT", "Continuous Audit Readiness\nEvidence graph + control checks", "proposed"),
        Node("P_INT", "Integration Layer\nERP, MES, LIMS, PLM, CRM", "platform"),
        Node("P_DATA", "Quality Data Platform\nCanonical model + event timeline", "platform"),
        Node("P_DASH", "Real-Time Quality Cockpit\nKPI trends + predictive alerts", "platform"),
    ]

    proposed_edges = [
        Edge("P_GOV", "P_ORCH"),
        Edge("P_ORCH", "P_DMS"),
        Edge("P_ORCH", "P_EQMS"),
        Edge("P_EQMS", "P_AI", "case context"),
        Edge("P_AI", "P_EQMS", "recommended actions"),
        Edge("P_EQMS", "P_TRAIN", "auto training impact"),
        Edge("P_EQMS", "P_AUDIT", "always-on evidence"),
        Edge("P_INT", "P_DATA", "streamed events"),
        Edge("P_DMS", "P_DATA"),
        Edge("P_EQMS", "P_DATA"),
        Edge("P_DATA", "P_DASH"),
        Edge("P_AI", "P_DASH", "predictive risk indicators"),
        Edge("P_DASH", "P_ORCH", "closed-loop improvement"),
    ]

    migration_edges = [
        Edge("C_QMS", "P_GOV", "digitize governance", "dashed"),
        Edge("C_DOC", "P_DMS", "migrate document lifecycle", "dashed"),
        Edge("C_EVENT", "P_EQMS", "standardize case taxonomy", "dashed"),
        Edge("C_CAPA", "P_EQMS", "convert workflow templates", "dashed"),
        Edge("C_APPROVAL", "P_ORCH", "replace email approvals", "dashed"),
        Edge("C_TRAIN", "P_TRAIN", "connect role matrix", "dashed"),
        Edge("C_AUDIT", "P_AUDIT", "continuous evidence model", "dashed"),
        Edge("C_DATA", "P_DATA", "unify quality data model", "dashed"),
    ]

    lines: list[str] = []
    lines.append("flowchart LR")
    lines.append("  %% Generated by generate_qms_system_diagram.py")
    lines.append("  subgraph CURRENT[\"Current QMS Structure (As-Is)\"]")
    for node in current_nodes:
        lines.append(render_node(node))
    lines.append("  end")

    lines.append("  subgraph TARGET[\"Proposed Digital QMS (To-Be)\"]")
    for node in proposed_nodes:
        lines.append(render_node(node))
    lines.append("  end")

    for edge in current_edges:
        lines.append("  " + render_edge(edge))
    for edge in proposed_edges:
        lines.append("  " + render_edge(edge))

    lines.append("  %% Migration mapping from current to proposed")
    for edge in migration_edges:
        lines.append("  " + render_edge(edge))

    lines.append("  classDef current fill:#FDE8C8,stroke:#AE6C00,stroke-width:1px,color:#1E1E1E;")
    lines.append("  classDef proposed fill:#DBF3E4,stroke:#1F7A45,stroke-width:1px,color:#1E1E1E;")
    lines.append("  classDef platform fill:#DDEBFF,stroke:#245EA8,stroke-width:1px,color:#1E1E1E;")
    lines.append("  classDef governance fill:#F5D9FF,stroke:#7A2B9A,stroke-width:1px,color:#1E1E1E;")
    lines.append("  classDef ai fill:#FFE4CC,stroke:#B55A00,stroke-width:1px,color:#1E1E1E;")

    for node in current_nodes + proposed_nodes:
        lines.append(f"  class {node.node_id} {node.css_class};")

    return "\n".join(lines) + "\n"


def build_markdown(mermaid_text: str) -> str:
    return f"""# QMS System Diagram: Current vs Proposed Digital Process\n\nThis diagram maps an existing, mostly manual QMS structure and a proposed AI-enabled\ndigital process architecture.\n\n## System Diagram\n\n```mermaid\n{mermaid_text}```\n\n## Suggested Rollout Sequence\n\n1. Foundation: define canonical quality data model and governance controls.\n2. Core digitization: implement orchestrated eQMS workflows for deviation/CAPA/change.\n3. Integration: connect ERP, MES, LIMS, and PLM to stream quality events.\n4. Intelligence: add AI triage, risk scoring, and recommendation layers.\n5. Optimization: activate real-time dashboards, alerts, and closed-loop improvement rules.\n\n## QMS Value Outcomes\n\n- Faster cycle time from issue detection to CAPA closure\n- Better audit readiness through continuous evidence capture\n- Earlier risk detection with predictive quality signals\n- Stronger traceability across documents, events, actions, and training\n"""


def write_outputs(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    mermaid_text = build_mermaid()

    mmd_path = output_dir / "qms_system_diagram.mmd"
    md_path = output_dir / "qms_system_diagram.md"

    mmd_path.write_text(mermaid_text, encoding="utf-8")
    md_path.write_text(build_markdown(mermaid_text), encoding="utf-8")

    return mmd_path, md_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate QMS system diagrams.")
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path(__file__).resolve().parent,
        help="Output directory for generated files (default: directory containing this script).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    outdir = args.outdir.resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    mmd_path, md_path = write_outputs(outdir)

    print(f"Generated Mermaid diagram: {mmd_path}")
    print(f"Generated Markdown diagram: {md_path}")


if __name__ == "__main__":
    main()
